### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sophist-UK**

### CODE REVIEW

**Comment by mylesduncanking** [comment]
I was going to tweak it so that instead of checking if "id" is present, check if the table already exists. If it exists - update it, if it doesn't add the id and timestamps columns to the column array automatically? Do you think that would be good?

**Comment by Sophist-UK** [comment]
No. Because for `down()` you won't be able to tell whether you need to drop columns or drop table.

**Comment by mylesduncanking** [comment]
Good point! The only reason I'm thinking not basing it off the 'id' type being present is you may use 'uuid' or you may have a pivot table that doesn't use either.

How about on the up()  we check if the table exists and for the down() we check if the table was created (using create_time from INFORMATION_SCHEMA.TABLES) at the same time the migration ran?

**Comment by Sophist-UK** [comment]
It's your code, so you need to choose, but I personally wouldn't recommend that approach.

I don't have any issues with SimpleMigration having some restrictions (like needing to use `id('key')` if you are creating a table). It is normal for simplification extensions to have less functionality. Alternatively code so that use of anything that creates a primary key is a trigger for create / drop table i.e. also `uuid` or use of `primary()` etc.

**Comment by mylesduncanking** [comment]
Made some changes to the README that encompass all of this but in better detail. I will close this PR but feel free to add another if you have more suggestions

**Comment by Sophist-UK** [comment]
Comments on the new Readme:

* Generally good - a much better explanation
* Could do with an explanation that it can create relationships as well as columns.
* IMO the docstring in this PR should be included in the example at the end
* The example at the end should probably lose the empty column modifiers so that it looks more like the first example.

**Pull request closed without merging**
